server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cachingproxy
    username: cachingproxy
    password: cachingproxy

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: cache-monitor
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.prasanna.cachingproxy.proxy
        spring.json.value.default.type: com.prasanna.cachingproxy.proxy.ProxyEvent

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
